// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * One flat config for the whole workspace.
 *
 * Deliberately NOT type-aware: type-checked linting would re-typecheck every
 * package on each run, and `pnpm typecheck` already does that in CI. This pass
 * is for the things the compiler does not catch. See docs/HANDOFF.md for
 * enabling type-aware rules later if the value justifies the runtime.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.next-build/**",
      "**/.next-dev/**",
      "**/.turbo/**",
      "**/coverage/**",
      "packages/db/drizzle/**",
      // Regenerated by Next on every build.
      "apps/web/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      /**
       * An unused variable is usually a half-finished edit. A leading
       * underscore is the escape hatch for a deliberately ignored argument.
       */
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      /**
       * `any` disables the type system exactly where a CRM handling regulated
       * data can least afford it. Warn rather than error so it surfaces in
       * review without blocking a legitimate escape hatch.
       */
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      /** Structured logging only: `logger` redacts, `console` does not. */
      "no-console": ["error", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-var": "error",
      "prefer-const": "error",
    },
  },

  {
    // Scripts and seeds are meant to talk to a human on a terminal.
    files: [
      "packages/db/src/scripts/**",
      "**/*.config.{ts,mts,mjs,js}",
      "eslint.config.mjs",
    ],
    rules: { "no-console": "off" },
  },

  {
    // Tests assert on shapes that are intentionally loose.
    files: ["**/__tests__/**", "**/*.test.{ts,tsx}"],
    rules: { "@typescript-eslint/no-explicit-any": "off", "no-console": "off" },
  },
);
