import {
  createCipheriv,
  createDecipheriv,
  createHash,
  randomBytes,
  createHmac,
  hkdfSync,
} from "node:crypto";
import { getEnv } from "@skincrm/config";

/**
 * Envelope encryption for per-clinic provider credentials (WhatsApp tokens, Meta
 * access tokens, SMTP passwords, TOTP secrets) and for raw third-party payloads.
 *
 * Design:
 *  - AES-256-GCM, so ciphertext is authenticated; tampering fails to decrypt.
 *  - A per-clinic data key derived from the master key via HKDF. One clinic's
 *    ciphertext cannot be decrypted with another clinic's derived key, which
 *    limits the blast radius of a logic bug that mixes up clinic ids.
 *  - The clinic id is bound as additional authenticated data, so a ciphertext
 *    copied from clinic A's row into clinic B's row fails to decrypt instead of
 *    silently yielding A's secret.
 *  - A version prefix so the format can change without a flag day.
 *
 * Root keys (D-93):
 *  - `CRYPTO_PROVIDER=local`: the root key is SHA-256 of CRYPTO_MASTER_KEY, a
 *    strong secret from the host's secret manager (D-75).
 *  - `CRYPTO_PROVIDER=aws-kms`: the root key is a 256-bit data key generated by
 *    AWS KMS and stored only in wrapped form (CRYPTO_WRAPPED_KEY). The process
 *    asks KMS to unwrap it once at start-up (`initCrypto()`) and keeps it in
 *    memory; the plaintext key never sits in configuration. Revoking the
 *    process's KMS permission makes every stored secret unreadable.
 *  - Rotation: older keys stay usable for decryption only
 *    (CRYPTO_PREVIOUS_WRAPPED_KEYS / CRYPTO_PREVIOUS_MASTER_KEYS). Each
 *    ciphertext names the derived key it used, so decryption picks the right
 *    one, and `pnpm db:rotate-keys` re-encrypts everything under the current key.
 */

const VERSION = "v1";
const ALGORITHM = "aes-256-gcm";
const IV_BYTES = 12; // 96 bits, the GCM standard
const KEY_BYTES = 32;

export interface EncryptedValue {
  /** `v1:<keyId>:<iv>:<tag>:<ciphertext>`, all base64url. Safe to store as text. */
  ciphertext: string;
}

interface RootKey {
  key: Buffer;
  /** Secret for HMAC-signed links made under this key (kept byte-compatible with D-75). */
  hmacSecret: Buffer;
}

interface KeyRing {
  current: RootKey;
  previous: RootKey[];
}

let ring: KeyRing | undefined;

/** Unwraps a KMS-encrypted data key. Replaceable in tests. */
export type KmsDecrypt = (ciphertextBlob: Buffer) => Promise<Buffer>;
let kmsDecrypt: KmsDecrypt | undefined;

export function setKmsDecrypt(fn: KmsDecrypt | undefined): void {
  kmsDecrypt = fn;
}

async function defaultKmsDecrypt(blob: Buffer): Promise<Buffer> {
  // Loaded only when KMS is used, so local installs don't need the AWS SDK.
  const { KMSClient, DecryptCommand } = await import("@aws-sdk/client-kms");
  const client = new KMSClient({});
  const out = await client.send(new DecryptCommand({ CiphertextBlob: blob, ...(getEnv().KMS_KEY_ID ? { KeyId: getEnv().KMS_KEY_ID } : {}) }));
  if (!out.Plaintext || out.Plaintext.length !== KEY_BYTES) throw new EncryptionError("KMS did not return a 256-bit key");
  return Buffer.from(out.Plaintext);
}

function localRoot(passphrase: string): RootKey {
  // A passphrase, not raw key material: hash it to a fixed width.
  return { key: createHash("sha256").update(passphrase, "utf8").digest(), hmacSecret: Buffer.from(passphrase, "utf8") };
}

function split(list: string | undefined): string[] {
  return (list ?? "").split(",").map((v) => v.trim()).filter(Boolean);
}

/**
 * Load the key ring. Required before any encryption when the provider is
 * aws-kms (the API and worker call it at start-up); a no-op otherwise.
 */
export async function initCrypto(): Promise<void> {
  const env = getEnv();
  const previousLocal = split(env.CRYPTO_PREVIOUS_MASTER_KEYS).map(localRoot);
  if (env.CRYPTO_PROVIDER !== "aws-kms") {
    ring = { current: localRoot(env.CRYPTO_MASTER_KEY!), previous: previousLocal };
    return;
  }
  if (!env.CRYPTO_WRAPPED_KEY) throw new EncryptionError("CRYPTO_PROVIDER=aws-kms needs CRYPTO_WRAPPED_KEY (run `pnpm crypto:new-key`)");
  const unwrap = kmsDecrypt ?? defaultKmsDecrypt;
  const fromKms = async (wrapped: string): Promise<RootKey> => {
    const key = await unwrap(Buffer.from(wrapped, "base64"));
    if (key.length !== KEY_BYTES) throw new EncryptionError("KMS did not return a 256-bit key");
    return { key, hmacSecret: createHmac("sha256", key).update("skincrm-signed-links").digest() };
  };
  const current = await fromKms(env.CRYPTO_WRAPPED_KEY);
  const previousKms = await Promise.all(split(env.CRYPTO_PREVIOUS_WRAPPED_KEYS).map(fromKms));
  ring = { current, previous: [...previousKms, ...previousLocal] };
}

/** Forget the loaded keys (tests, and after changing key configuration). */
export function resetCrypto(): void {
  ring = undefined;
}

function keyRing(): KeyRing {
  if (ring) return ring;
  const env = getEnv();
  if (env.CRYPTO_PROVIDER === "aws-kms") {
    throw new EncryptionError("Encryption keys aren't loaded: call initCrypto() at start-up when CRYPTO_PROVIDER=aws-kms");
  }
  ring = { current: localRoot(env.CRYPTO_MASTER_KEY!), previous: split(env.CRYPTO_PREVIOUS_MASTER_KEYS).map(localRoot) };
  return ring;
}

/** Secrets for signed links: sign with the first, accept any (survives rotation). */
export function linkSigningSecrets(): Buffer[] {
  const r = keyRing();
  return [r.current.hmacSecret, ...r.previous.map((k) => k.hmacSecret)];
}

/** Derive a stable per-clinic key. Same clinic id always yields the same key. */
function deriveClinicKey(root: Buffer, clinicId: string): Buffer {
  const derived = hkdfSync("sha256", root, Buffer.from(clinicId, "utf8"), Buffer.from("skincrm-clinic-credentials", "utf8"), KEY_BYTES);
  return Buffer.from(derived);
}

/** Short, non-secret fingerprint of the key used, so the right key can be found. */
function keyId(key: Buffer): string {
  return createHash("sha256").update(key).digest("hex").slice(0, 8);
}

export function encryptForClinic(clinicId: string, plaintext: string): string {
  const key = deriveClinicKey(keyRing().current.key, clinicId);
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  cipher.setAAD(Buffer.from(clinicId, "utf8"));
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return [VERSION, keyId(key), iv.toString("base64url"), tag.toString("base64url"), ciphertext.toString("base64url")].join(
    ":",
  );
}

export function decryptForClinic(clinicId: string, stored: string): string {
  const parts = stored.split(":");
  if (parts.length !== 5) throw new EncryptionError("Malformed ciphertext");
  const [version, storedKeyId, ivPart, tagPart, dataPart] = parts as [string, string, string, string, string];
  if (version !== VERSION) throw new EncryptionError(`Unsupported ciphertext version ${version}`);

  const r = keyRing();
  const candidates = [r.current, ...r.previous].map((root) => deriveClinicKey(root.key, clinicId));
  // The named key first; the rest only as a fallback.
  candidates.sort((a, b) => Number(keyId(b) === storedKeyId) - Number(keyId(a) === storedKeyId));
  for (const key of candidates) {
    try {
      const decipher = createDecipheriv(ALGORITHM, key, Buffer.from(ivPart, "base64url"));
      decipher.setAAD(Buffer.from(clinicId, "utf8"));
      decipher.setAuthTag(Buffer.from(tagPart, "base64url"));
      return Buffer.concat([decipher.update(Buffer.from(dataPart, "base64url")), decipher.final()]).toString("utf8");
    } catch {
      // Try the next key.
    }
  }
  // Wrong clinic, tampered ciphertext, or a key that is no longer configured.
  throw new EncryptionError("Unable to decrypt value for this clinic");
}

/** True when the value was encrypted under an older key (rotation pending). */
export function isEncryptedUnderOldKey(clinicId: string, stored: string): boolean {
  const parts = stored.split(":");
  if (parts.length !== 5 || parts[0] !== VERSION) return false;
  return parts[1] !== keyId(deriveClinicKey(keyRing().current.key, clinicId));
}

/** Matches a value this module produced, for finding ciphertext inside JSON. */
export const CIPHERTEXT_PATTERN = /^v1:[0-9a-f]{8}:[A-Za-z0-9_-]+:[A-Za-z0-9_-]+:[A-Za-z0-9_-]*$/;

export class EncryptionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EncryptionError";
  }
}

/**
 * One-way fingerprint for deduplicating stored raw payloads without keeping a
 * second readable copy (PRD 5: "raw payload reference/hash").
 */
export function payloadFingerprint(payload: unknown): string {
  return createHash("sha256").update(stableStringify(payload), "utf8").digest("hex");
}

/** Deterministic JSON so key order cannot change a fingerprint. */
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`);
  return `{${entries.join(",")}}`;
}
